### ISSUE TITLE
`ember-a11y-testing` updates and simplification

### ISSUE THREAD

**Issue by scalvert** [ember-a11y/ember-a11y-testing#207]
This addon has largely been left untouched since its initial creation. There have been a number of default Ember blueprint updates (outside of this repo), which were hard to pull in due to it being so out-of-date.

In addition to this, the `@ember/test-helpers` addon, which is one of the underpinnings of Ember's testing system, had evolved to include some [new and useful APIs](https://github.com/emberjs/ember-test-helpers/pull/878) that could positively impact the direction of this addon. More specifically, the new hooks API could be leveraged to automatically wire up accessibility audits in a hands-off manner, allowing apps and addons to progress their code to being more accessible. 

Based on the above, there are a number of updates to this addon that are proposed:

- [x] Ensure it's up-to-date with the latest blueprint. (#181, #182, #187, #190)
- [x] Convert to TypeScript. Adding TS allows the APIs to be cleaned up and validated, in terms of this public interfaces. (#184, #204)
- [x] Update linting. (#188)
- [x] Converting to use Github actions vs. Travis (faster CI execution). (#192, #193)
- [x] Convert `a11yAudit` failure to use `throw` vs. `Ember.assert`. (#201)
- [x] Implement new `setupGlobalA11yHooks` API, which leverages the new hooks API in `@ember/test-helpers`. (Issue: #186, PR: #200)
- [x] Drop support for `moduleForAcceptance`. This API is deprecated. (#199)
- [x] Deprecate `a11yAuditIf` (#203)
- [x] Remove non-test related components and infrastructure (#205)
- [x] Implement new reporter system, allowing for the custom reporting of violations (#210)
- [x] Update README with all API and functional changes.

Once the above are completed this addon should be in a stable state, and a new major version should be released.

**Comment by scalvert** [comment]
All of the above have been merged, so closing this.
